### ISSUE TITLE
feature: bookmark search

### ISSUE THREAD

**Issue by abdulhdr1** [gustavo-fior/bookmarks#1]
I have a list of bookmarks and I want to search through them
Ideally, it does not only match the title but also the og description
A more sophisticated approach would be to integrate something like [algolia](https://www.algolia.com/) that uses fancy search stuff, or we could implement the fancy stuff on our side  :thinking:

**Comment by getmindapp** [comment]
done

**Comment by gustavo-fior** [comment]
done
